### ISSUE TITLE
Applying for GitHub publisher verification for "Terratest Test Runner" Action.

### ISSUE THREAD

**Issue by vigor-vavan** [cloudposse/github-action-terratest#9]
Description

I’m writing regarding the GH Action [Terratest Test Runner](https://github.com/marketplace/actions/terratest-test-runner)

Our project is starting to migrate the CI/CD to GH Actions and we are interested to use your Actions.
Providing some context, our Security team requires the "Creator Verified by GitHub" badge to start the internal GHA verification process, due to this we are blocked to use unverified Actions.

We would be grateful if you could start the GH Action verification process, as it would help us greatly.

I believe it must improve your impact in the whole GitHub community as a partner organization and also, you are letting us use your actions.

You can find more helpful information in the following articles from GitHub Docs as a good starting point on the process.

[Applying for publisher verification for your organization](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization)
[About marketplace badges](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges)

**Comment by osterman** [comment]
Thanks! This is now done.

![CleanShot 2023-02-14 at 09 32 27](https://user-images.githubusercontent.com/52489/218783601-f56ab730-0530-4a99-8244-b39212f35842.png)
